# pytorch fundamentals

In [36]:
import torch

In [2]:
torch.__version__


'2.1.0+cpu'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [8]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [9]:
vector.ndim , vector.shape

(1, torch.Size([3]))

In [11]:
matrix = torch.tensor([[1, 2],
                      [3, 4]])

In [13]:
# Check number of dimensions
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
# Tensor
tensorr = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensorr

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
# Check number of dimensions for TENSOR
tensorr.ndim

3

In [17]:
tensorr.shape

torch.Size([1, 3, 3])

In [22]:
tensor2 = torch.tensor([[[1, 2, 3],
                         [4, 5, 6]]])
tensor2


tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [23]:
tensor2.ndim , tensor2.shape

(3, torch.Size([1, 2, 3]))

In [24]:
# random tensors 
random_tensor = torch.rand(size=(3,4))
random_tensor , random_tensor.shape, random_tensor.ndim, random_tensor.dtype

(tensor([[0.4526, 0.5344, 0.5975, 0.7158],
         [0.4974, 0.6794, 0.3662, 0.1107],
         [0.8688, 0.9420, 0.5530, 0.4400]]),
 torch.Size([3, 4]),
 2,
 torch.float32)

In [25]:
random_img = torch.rand(size=(224,224,3))
random_img.shape, random_img.ndim


(torch.Size([224, 224, 3]), 3)

In [28]:
# zeros and ones

zeros_tensor = torch.zeros(size=(3,4))
ones_tensor = torch.ones(size=(4,3))
zeros_tensor, zeros_tensor.shape, zeros_tensor.ndim, ones_tensor.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]),
 2,
 torch.float32)

In [30]:
ones_tensor, ones_tensor.shape, ones_tensor.ndim, ones_tensor.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([4, 3]),
 2,
 torch.float32)

In [31]:
# range tensors

range_tensor = torch.arange(start=0, end=10, step=0.5)
range_tensor, range_tensor.shape, range_tensor.ndim, range_tensor.dtype

(tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
         4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
         9.0000, 9.5000]),
 torch.Size([20]),
 1,
 torch.float32)

In [34]:
# Can also create a tensor of zeros similar to another tensor
makeitzero = torch.zeros_like(input=range_tensor) # will have same shape
makeitzero

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
 # Getting information from tensors

some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.3883, 0.0163, 0.8994, 0.6190],
        [0.4947, 0.2157, 0.0035, 0.8270],
        [0.4144, 0.8374, 0.3967, 0.3691]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


#

# Manipulating tensors (tensor operations)

In [37]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [41]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [42]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [43]:
tensor

tensor([1, 2, 3])

In [46]:
print(tensor, "*", tensor , "Equals:", tensor * tensor )


tensor([1, 2, 3]) * tensor([1, 2, 3]) Equals: tensor([1, 4, 9])


In [47]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [48]:
# Element-wise matrix mutlication
tensor * tensor


tensor([1, 4, 9])

In [49]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
#:D