In [1]:
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5790, 0.9753],
        [0.5081, 0.0787]]) 



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5865, 0.6233, 0.8318],
        [0.4534, 0.1474, 0.8430]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
# We move our tensor to the GPU ((((((if available)))))))
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# Joining tensors
# torch.cat() concatenates the given sequence along an existing dimension.
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
# Define two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Stack tensors along dimension 0
stacked_dim0 = torch.stack((tensor1, tensor2), dim=0)
print("Stacked along dimension 0:", stacked_dim0)

# Stack tensors along dimension 1
stacked_dim1 = torch.stack((tensor1, tensor2), dim=1)
print("Stacked along dimension 1:", stacked_dim1)

Stacked along dimension 0: tensor([[1, 2, 3],
        [4, 5, 6]])
Stacked along dimension 1: tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [14]:
import torch

# Define two tensors of shape (2, 3, 4)
tensor1 = torch.tensor([[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                        [[13, 14, 15, 16],
                         [17, 18, 19, 20],
                         [21, 22, 23, 24]]])

tensor2 = torch.tensor([[[25, 26, 27, 28],
                         [29, 30, 31, 32],
                         [33, 34, 35, 36]],
                        [[37, 38, 39, 40],
                         [41, 42, 43, 44],
                         [45, 46, 47, 48]]])

# Stack tensors along dimension 0
stacked_dim0 = torch.stack((tensor1, tensor2), dim=0)
print("Stacked along dimension 0:", stacked_dim0.shape)
print("Stacked along dimension 1:", stacked_dim0)
# Stack tensors along dimension 1
stacked_dim1 = torch.stack((tensor1, tensor2), dim=1)
print("Stacked along dimension 1:", stacked_dim1.shape)
print("Stacked along dimension 1:", stacked_dim1)


# Stack tensors along dimension 2
stacked_dim2 = torch.stack((tensor1, tensor2), dim=2)
print("Stacked along dimension 2:", stacked_dim2.shape)
print("Stacked along dimension 1:", stacked_dim2)


Stacked along dimension 0: torch.Size([2, 2, 3, 4])
Stacked along dimension 1: tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]],


        [[[25, 26, 27, 28],
          [29, 30, 31, 32],
          [33, 34, 35, 36]],

         [[37, 38, 39, 40],
          [41, 42, 43, 44],
          [45, 46, 47, 48]]]])
Stacked along dimension 1: torch.Size([2, 2, 3, 4])
Stacked along dimension 1: tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[25, 26, 27, 28],
          [29, 30, 31, 32],
          [33, 34, 35, 36]]],


        [[[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]],

         [[37, 38, 39, 40],
          [41, 42, 43, 44],
          [45, 46, 47, 48]]]])
Stacked along dimension 2: torch.Size([2, 3, 2, 4])
Stacked along dimension 1: tensor([[[[ 1,  2,  3,  4],
          [25, 26, 27, 28]],

         [[

In [15]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [16]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [17]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [18]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [19]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [20]:
n = np.ones(5)
t = torch.from_numpy(n)

In [21]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
