# Tensor Operations

In [1]:
import torch

In [2]:
v = torch.arange(0,10,1)
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
v.min(), v.max()

(tensor(0), tensor(9))

In [7]:
v.argmax(), v.argmin()

(tensor(9), tensor(0))

In [8]:
v2 = torch.arange(0,20,2)
v2


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
#argmax returns the index of maximum value
#argmin returns the index of minimum value
v2.argmax(), v2.argmin()

(tensor(9), tensor(0))

In [10]:
min_index = v2.argmin()
min_index

tensor(0)

In [11]:
max_index = v2.argmax()
max_index

tensor(9)

In [13]:
flaot_tensor = torch.arange(0,10,1)
flaot_tensor , flaot_tensor.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

# tensor transpose

In [29]:
random_tensor = torch.rand(2,6)

In [30]:
random_tensor

tensor([[0.9914, 0.6407, 0.7953, 0.8803, 0.8091, 0.8531],
        [0.0836, 0.0924, 0.3503, 0.9607, 0.8140, 0.0551]])

In [31]:
random_tensor_transpose = torch.transpose(random_tensor, dim0=1, dim1=0)

random_tensor_transpose

tensor([[0.9914, 0.0836],
        [0.6407, 0.0924],
        [0.7953, 0.3503],
        [0.8803, 0.9607],
        [0.8091, 0.8140],
        [0.8531, 0.0551]])

In [32]:
random_tensor_transpose_V2 = random_tensor.t()

In [33]:
random_tensor_transpose_V2

tensor([[0.9914, 0.0836],
        [0.6407, 0.0924],
        [0.7953, 0.3503],
        [0.8803, 0.9607],
        [0.8091, 0.8140],
        [0.8531, 0.0551]])

# mean

In [34]:
random_tensor_transpose_V2.mean()

tensor(0.6105)

In [35]:
# mean tensor takes input dtype as float point

# reshape

In [37]:
v2 , v2.shape, v2.dtype

(tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 torch.Size([10]),
 torch.int64)

In [40]:
reshaped1 = v2.reshape(5,-1)
reshaped2 = v2.reshape(2,-1)
reshaped1, reshaped2

(tensor([[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14],
         [16, 18]]),
 tensor([[ 0,  2,  4,  6,  8],
         [10, 12, 14, 16, 18]]))

In [41]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [42]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

# stacked tensor


##### concatenate a sequence of tensors together along another dimension

In [47]:
x = torch.rand(4,4)

In [48]:
x 

tensor([[0.0174, 0.2329, 0.2741, 0.3443],
        [0.2336, 0.8370, 0.3503, 0.0119],
        [0.3066, 0.0978, 0.1302, 0.4405],
        [0.7680, 0.6126, 0.6007, 0.7412]])

In [50]:
stacked_tensor = torch.stack([x,x,x,x], dim=0)
stacked_tensor

tensor([[[0.0174, 0.2329, 0.2741, 0.3443],
         [0.2336, 0.8370, 0.3503, 0.0119],
         [0.3066, 0.0978, 0.1302, 0.4405],
         [0.7680, 0.6126, 0.6007, 0.7412]],

        [[0.0174, 0.2329, 0.2741, 0.3443],
         [0.2336, 0.8370, 0.3503, 0.0119],
         [0.3066, 0.0978, 0.1302, 0.4405],
         [0.7680, 0.6126, 0.6007, 0.7412]],

        [[0.0174, 0.2329, 0.2741, 0.3443],
         [0.2336, 0.8370, 0.3503, 0.0119],
         [0.3066, 0.0978, 0.1302, 0.4405],
         [0.7680, 0.6126, 0.6007, 0.7412]],

        [[0.0174, 0.2329, 0.2741, 0.3443],
         [0.2336, 0.8370, 0.3503, 0.0119],
         [0.3066, 0.0978, 0.1302, 0.4405],
         [0.7680, 0.6126, 0.6007, 0.7412]]])

# squeeze method

In [52]:
tensor_mod = tensor.reshape(1, -1)

In [53]:
tensor_mod, tensor_mod.shape

(tensor([[0.5094, 0.2445, 0.5675, 0.8581, 0.1823, 0.4298, 0.4019, 0.4713, 0.3279,
          0.0902, 0.9274, 0.6760, 0.8478, 0.0229, 0.8725, 0.1754]]),
 torch.Size([1, 16]))

In [54]:
# squeeze removves the extra dimensions (1, 16) will be (, 16)
squeeze_tensor = tensor_mod.squeeze()
squeeze_tensor, squeeze_tensor.shape

(tensor([0.5094, 0.2445, 0.5675, 0.8581, 0.1823, 0.4298, 0.4019, 0.4713, 0.3279,
         0.0902, 0.9274, 0.6760, 0.8478, 0.0229, 0.8725, 0.1754]),
 torch.Size([16]))

# unsqueeze method 

In [56]:
unsqueeze_tensorV1 = squeeze_tensor.unsqueeze(dim=1)


In [57]:
unsqueeze_tensorV1, unsqueeze_tensorV1.shape

(tensor([[0.5094],
         [0.2445],
         [0.5675],
         [0.8581],
         [0.1823],
         [0.4298],
         [0.4019],
         [0.4713],
         [0.3279],
         [0.0902],
         [0.9274],
         [0.6760],
         [0.8478],
         [0.0229],
         [0.8725],
         [0.1754]]),
 torch.Size([16, 1]))

# permute

In [60]:
i = torch.rand(224,228,3)
i

tensor([[[0.1542, 0.0078, 0.7580],
         [0.0819, 0.0541, 0.7717],
         [0.0456, 0.2567, 0.0044],
         ...,
         [0.2521, 0.4003, 0.8561],
         [0.5419, 0.8383, 0.1248],
         [0.2150, 0.5499, 0.1768]],

        [[0.9821, 0.7942, 0.8394],
         [0.7054, 0.0554, 0.4402],
         [0.8542, 0.1240, 0.7711],
         ...,
         [0.0144, 0.3107, 0.7047],
         [0.6540, 0.1386, 0.0316],
         [0.4117, 0.6191, 0.3328]],

        [[0.1176, 0.8373, 0.4453],
         [0.4470, 0.6028, 0.0816],
         [0.8165, 0.5089, 0.3937],
         ...,
         [0.0959, 0.0335, 0.2336],
         [0.6945, 0.7351, 0.6220],
         [0.7910, 0.6853, 0.7296]],

        ...,

        [[0.2268, 0.0268, 0.9787],
         [0.8480, 0.9751, 0.7358],
         [0.2123, 0.8764, 0.9462],
         ...,
         [0.9699, 0.3076, 0.0857],
         [0.4035, 0.3533, 0.7423],
         [0.1215, 0.7053, 0.5593]],

        [[0.1174, 0.5423, 0.7725],
         [0.9901, 0.6474, 0.3384],
         [0.

In [61]:
i.shape

torch.Size([224, 228, 3])

In [65]:
# i want to swap the third index (2) with the first index (0)
i_permuted = torch.permute(i ,(2, 1, 0))
i_permuted.shape

torch.Size([3, 228, 224])