In [1]:
import torch 

# access indices

In [21]:
# The first dimension (size 3) corresponds to the number of matrices in the tensor.
# The second dimension (size 2) represents the number of rows in each matrix.
# The third dimension (size 4) represents the number of columns in each matrix.
x = torch.rand(3,2,4)
x

tensor([[[0.8762, 0.1401, 0.2667, 0.4166],
         [0.7902, 0.4435, 0.0779, 0.9118]],

        [[0.5291, 0.9686, 0.7481, 0.4444],
         [0.9616, 0.0889, 0.4610, 0.4453]],

        [[0.0417, 0.3777, 0.1148, 0.8538],
         [0.3582, 0.0865, 0.7216, 0.9618]]])

In [22]:
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[0.8762, 0.1401, 0.2667, 0.4166],
        [0.7902, 0.4435, 0.0779, 0.9118]])
Second square bracket: tensor([0.8762, 0.1401, 0.2667, 0.4166])
Third square bracket: 0.8762301206588745


In [23]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[0.8762, 0.1401, 0.2667, 0.4166],
        [0.5291, 0.9686, 0.7481, 0.4444],
        [0.0417, 0.3777, 0.1148, 0.8538]])

In [29]:
vv = torch.arange(1,10)
v = vv.reshape(1, 3, 3)
v, v.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [30]:
# Get all values of 0th dimension and the 0 index of 1st dimension
v[:, 0]

tensor([[1, 2, 3]])

In [32]:
# Get all values of 0th & 1st dimensions 
#but only index 1 of 2nd dimension
v[:, :, 1]

tensor([[2, 5, 8]])

In [33]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
v[0, 0, :] # same as v[0][0]

tensor([1, 2, 3])

In [34]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [35]:
type(tensor)

torch.Tensor

In [36]:
# tensor to numpy nd array
x = torch.arange(0,10,1)
x , type(x)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Tensor)

In [37]:
x_numpy = x.numpy()
type(x_numpy)

numpy.ndarray

In [38]:
torch.manual_seed(42)
random_tensor = torch.rand(2,2)
random_tensor

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [40]:
!nvidia-smi

Sun Jan 28 11:36:48 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.78       Driver Version: 512.78       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   58C    P0    17W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [42]:
#device agonstic code
device = 'cuda' if torch.cuda.is_available else 'cpu'

In [43]:
device

'cuda'

In [44]:
#check for other GPU's
torch.cuda.device_count()

0

In [45]:
tensor = torch.tensor([2,5])
tensor , tensor.device

(tensor([2, 5]), device(type='cpu'))

In [46]:
tensor_gpu = tensor.to('cuda')

AssertionError: Torch not compiled with CUDA enabled

In [47]:
print(torch.cuda.is_available())


False
